services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile  # Reference your Next.js Dockerfile
    container_name: blog
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    expose:
      - "3000"  # Expose port 3000 for internal communication
    networks:
      - blognetwork


  # Uncomment the following to use postgres
  postgres:
    restart: always
    image: postgres:latest
    volumes:
     - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Map to a different host port to avoid conflicts
    env_file:
      - .env
    networks:
      - blognetwork

  caddy_for_blog:
    image: caddy
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - blognetwork

networks:
  blognetwork:
    driver: bridge

volumes:
  data:
  pgdata:
  node_modules:
  caddy_data:
  caddy_config:
