[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/notes/01-hello-note"
  to = "/"
  status = 410

[[redirects]]
  from = "/articles"
  to = "/posts"
  status = 301

[[redirects]]
    from = "/admin/*"
    to = "/admin"
    status = 301
    force = true